server:
  port: 8000 # El Gateway es la única puerta de entrada pública (Puerto 8000)

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          # URL del Identity Provider (Keycloak). El Gateway consultará esta URL 
          # para obtener las llaves públicas y validar la firma de los tokens JWT.
          issuer-uri: http://localhost:8080/realms/food-ordering

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            # Configuración Global de CORS
            # Permite que una aplicación web alojada en otro puerto (ej. Angular en 4200) consuma nuestra API.
            cors-configurations:
              "[/**]":
                allowedOrigins: "http://localhost:4200"
                allowedMethods: "*"
                allowedHeaders: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      # Definimos el menú desplegable en Swagger UI para cambiar entre microservicios
      - name: catalog-service
        url: /v3/api-docs/catalog-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: order-service
        url: /v3/api-docs/order-service
      - name: payment-service
        url: /v3/api-docs/payment-service
      - name: delivery-service
        url: /v3/api-docs/delivery-service

# Configuración de Actuator para Observabilidad (Preparado para Prometheus/Grafana)
management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
      # Exponemos rutas vitales: health (para ver si el servicio está vivo) y prometheus (para métricas)
        include: health,info,prometheus,gateway
  # Opcional pero recomendado para métricas más ricas:
  metrics:
    tags:
      application: ${spring.application.name} # Etiqueta las métricas con el nombre del gateway
