apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - catalog-service/deployment.yaml
  - catalog-service/service.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - payment-service/deployment.yaml
  - payment-service/service.yaml
  - delivery-service/deployment.yaml
  - delivery-service/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
